# NODEJS Base
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t cdnd-03-ms-rp .
  - docker tag cdnd-03-ms-rp chk86/cdnd-03-ms-rp:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chk86/cdnd-03-ms-rp
